apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordermgr
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ordermgr
    spec:
      containers:
      - name: ordermgr 
        image: demo/kubeotprom-ordermgr:v1
        ports:
        - name: web
          containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: ordermgr
          - name: JAEGER_AGENT_HOST
            value: jaeger-all-in-one-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: ACCOUNTMGR_URL
            value: "http://accountmgr:8080"
---
kind: Service
apiVersion: v1
metadata:
  name: ordermgr
  labels:
    app: ordermgr
spec:
  type: NodePort
  selector:
    app: ordermgr
  ports:
  - name: web
    nodePort: 31900
    port: 8080
    protocol: TCP
    targetPort: web
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: ordermgr
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: ordermgr
  endpoints:
  - port: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accountmgr
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: accountmgr
    spec:
      containers:
      - name: accountmgr 
        image: demo/kubeotprom-accountmgr:v1
        ports:
        - name: web
          containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: accountmgr
          - name: JAEGER_AGENT_HOST
            value: jaeger-all-in-one-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: accountmgr
  labels:
    app: accountmgr
spec:
  type: NodePort
  selector:
    app: accountmgr
  ports:
  - name: web
    nodePort: 31901
    port: 8080
    protocol: TCP
    targetPort: web
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: accountmgr
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: accountmgr
  endpoints:
  - port: web

